#!/bin/sh

if ! [ -x "$(command -v scanimage)" ]; then
  echo 'Error: "scanimage" is not installed.' >&2
  exit 1
fi

if ! [ -x "$(command -v convert)" ]; then
  echo 'Error: "imagemagik" is not installed.' >&2
  exit 1
fi

if [ -z "$1" ]
then
    echo "Usage: $0 <NO_OF_PAGES> <OUTPUT_FILE>" >&2
    exit 1
fi

if [ -z "$2" ]
then
    echo "Usage: $0 <NO_OF_PAGES> <OUTPUT_FILE>"
    exit 1
fi

pages="$1"
file="$2"

if [ $1 -le 0 ]
then
    echo "NO_OF_PAGES have to be greater than or equal to 1"
    exit 1
fi

DEVICES=$(scanimage -L)

if [ -z "$DEVICES" ]
then
    echo "No scanning device found. Please make sure you are installed the correct drivers."
    exit 1
fi

DEVICE=$(echo "$DEVICES" | dmenu -l 20 -p "Choose Device" | cut -d\` -f2 | cut -d\' -f1)

if [ -z "$DEVICE" ]
then
    exit 1
fi

echo "Using device $DEVICE"

while [ $pages -gt 0 ]
do
    echo "Press Enter to scan"
    read
    TEMP_TIFF=$(mktemp --suffix=.tiff)
    scanimage -d "$DEVICE" --format jpeg > "img-$pages.jpg"
    pages=$(expr $pages - 1)
done

echo "Creating $2 file"
convert *.jpg -auto-orient "$2"
